### ISSUE TITLE
When use option --diff and --yaml , the report file content has a problem.

### ISSUE THREAD

**Issue by echohn** [AlDanial/cloc#127]
When I  use `cloc --diff a.zip  b.zip  --yaml --out=a.yml` command ,  I found the report file content like this:

```yaml
---
# github.com/AlDanial/cloc
header : 
...

same : 
    language : CSS
    files_count : 3
    blank : 0
    comment : 25
    code : 2
    language : JavaScript
    files_count : 38
    blank : 0
    comment : 131
    code : 2177
    language : HTML
    files_count : 3
    blank : 0
    comment : 3
    code : 182

...
```

The 'same' key in this file have multiple key named 'language' and  'blank', etc.

If I parse the report file , the last value of these same keys will replace previous same keys.

The parse result will lose much of report content  . I think this should be a problem.
